# Generated by Django 5.2.17 on 2026-09-02 01:32

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("ga4", "Google Analytics 4"),
                            ("search_console", "Google Search Console"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_authorization", "Pending authorization"),
                            (
                                "awaiting_resource_selection",
                                "Awaiting resource selection",
                            ),
                            ("connected", "Connected"),
                            ("error", "Error"),
                            ("reauth_required", "Reauthorization required"),
                            ("disconnected", "Disconnected"),
                        ],
                        default="pending_authorization",
                        max_length=32,
                    ),
                ),
                (
                    "external_resource_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "external_resource_label",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("external_resource_meta", models.JSONField(blank=True, default=dict)),
                (
                    "google_account_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                (
                    "granted_scopes",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("last_health_check_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_successful_check_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "last_error_code",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("last_error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "connected_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="connected_integrations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="projects.project",
                    ),
                ),
            ],
            options={
                "ordering": ["provider", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("project", "provider"),
                        name="unique_integration_per_project",
                    )
                ],
            },
        ),
    ]
