# Generated by Django 5.2.17 on 2026-09-04 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_integrationcredential_oauthauthorizationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationconnection",
            name="lifecycle_generation",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="oauthauthorizationrequest",
            name="connection_generation",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
