# Generated by Django 5.2.17 on 2026-09-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                choices=[
                    (
                        "integration.authorization_started",
                        "Integration authorization started",
                    ),
                    ("integration.authorized", "Integration authorized"),
                    (
                        "integration.authorization_failed",
                        "Integration authorization failed",
                    ),
                    ("integration.connected", "Integration connected"),
                    ("integration.reconnected", "Integration reconnected"),
                    ("integration.disconnected", "Integration disconnected"),
                    ("integration.resource_selected", "Integration resource selected"),
                ],
                max_length=64,
            ),
        ),
    ]
