"""The Google OAuth 2.0 web-server flow.

Protocol behaviour comes from google-auth-oauthlib, Google's own maintained
library, rather than hand-built requests. Verified against current Google
documentation on 2026-09-02 — see docs/V1_TECHNICAL_DESIGN.md §7 for the URLs.

Notes on the parameters this sends:

* ``access_type=offline`` — the backend must reach the selected resource for
  health checks with no user present, so offline access is a real requirement.
* ``include_granted_scopes=true`` — incremental authorization, as Google
  recommends. Connecting a second provider with the same Google account adds
  to the existing grant instead of displacing it.
* ``prompt`` is **not** sent by default. It is set to ``consent`` only when a
  refresh token must actually be re-acquired.
* PKCE (``code_challenge``/``code_challenge_method=S256``) is sent because
  google-auth-oauthlib generates a verifier by default for this flow. Keeping
  the library's default costs one stored verifier and no custom protocol code;
  overriding a maintained library's security default would need a reason.
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass

from django.conf import settings
from google_auth_oauthlib.flow import Flow

from .errors import TokenExchangeFailed

# oauthlib raises on ANY difference between requested and granted scope. That
# check is both too blunt and too weak here: Google legitimately returns a
# different scope set for `include_granted_scopes`, and Google's own docs warn
# that "the scope included in your request may not match the scope included in
# your response, even if the user granted all requested scopes". Relaxing it
# does not weaken anything, because exchange_code() below verifies the required
# provider scope explicitly against `granted_scopes` and refuses to progress
# without it.
os.environ.setdefault("OAUTHLIB_RELAX_TOKEN_SCOPE", "1")

logger = logging.getLogger(__name__)

AUTH_URI = "https://accounts.google.com/o/oauth2/v2/auth"
TOKEN_URI = "https://oauth2.googleapis.com/token"


@dataclass(frozen=True)
class AuthorizationRedirect:
    url: str
    code_verifier: str


@dataclass(frozen=True)
class TokenResult:
    access_token: str
    refresh_token: str
    expires_at: object | None
    granted_scopes: tuple[str, ...]


def _client_config() -> dict:
    return {
        "web": {
            "client_id": settings.GOOGLE_CLIENT_ID,
            "client_secret": settings.GOOGLE_CLIENT_SECRET,
            "auth_uri": AUTH_URI,
            "token_uri": TOKEN_URI,
        }
    }


def _flow(scopes: list[str], *, code_verifier: str | None = None) -> Flow:
    flow = Flow.from_client_config(
        _client_config(),
        scopes=scopes,
        redirect_uri=settings.GOOGLE_OAUTH_REDIRECT_URI,
    )
    if code_verifier:
        flow.code_verifier = code_verifier
    return flow


def build_authorization_redirect(
    *, scopes: list[str], state: str, force_consent: bool = False
) -> AuthorizationRedirect:
    """Build the Google consent URL for one provider's scopes.

    ``state`` is generated by the caller so that only its hash is persisted.
    """
    flow = _flow(scopes)
    params = {
        "access_type": "offline",
        "include_granted_scopes": "true",
        "state": state,
    }
    if force_consent:
        # Only when a new refresh token is actually needed: Google issues one
        # on first authorization for a client/account/scope combination, so
        # re-consent is the way to obtain another. Never sent by default.
        params["prompt"] = "consent"

    url, _returned_state = flow.authorization_url(**params)
    return AuthorizationRedirect(url=url, code_verifier=flow.code_verifier or "")


def exchange_code(*, code: str, scopes: list[str], code_verifier: str) -> TokenResult:
    """Exchange an authorization code for tokens, server to server.

    Never logs the code, the token response, or the provider's raw error text:
    a failure is mapped to our own error before anything reaches a log.
    """
    flow = _flow(scopes, code_verifier=code_verifier)
    try:
        flow.fetch_token(code=code)
    except Exception as exc:
        # Deliberately does not include str(exc): oauthlib error text can echo
        # the request body, which contains the code and the client secret.
        logger.warning(
            "Google token exchange failed (%s)", type(exc).__name__
        )
        raise TokenExchangeFailed from exc

    credentials = flow.credentials
    # Google may grant fewer scopes than requested (granular consent), so read
    # what was actually granted rather than assuming the request was honoured.
    granted = tuple(getattr(credentials, "granted_scopes", None) or credentials.scopes or ())
    return TokenResult(
        access_token=credentials.token or "",
        refresh_token=credentials.refresh_token or "",
        expires_at=credentials.expiry,
        granted_scopes=granted,
    )
