#!/usr/bin/env bash
# Regenerate the pinned Python dependency locks.
#
# Approach: install the direct requirements into a throwaway virtualenv and
# freeze the fully resolved set. No extra tooling — pip and venv only, both of
# which are already required to run the project. Run this after editing
# apps/api/requirements.txt or apps/api/requirements-dev.txt, and commit the
# regenerated .lock.txt files alongside the change.
#
#   ./scripts/lock-python-deps.sh
#
# The locks pin exact versions for a Linux x86_64 / CPython 3.11+ target, which
# is what development and the production containers both use.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
API_DIR="$REPO_ROOT/apps/api"
PYTHON="${PYTHON:-python3}"

lock() {
    local source_file="$1"
    local lock_file="$2"
    local workdir
    workdir="$(mktemp -d)"
    trap 'rm -rf "$workdir"' RETURN

    echo "Resolving $source_file …"
    "$PYTHON" -m venv "$workdir/venv"
    "$workdir/venv/bin/pip" install --quiet --upgrade pip
    "$workdir/venv/bin/pip" install --quiet -r "$API_DIR/$source_file"

    {
        echo "# Generated by scripts/lock-python-deps.sh — do not edit by hand."
        echo "# Source: apps/api/$source_file"
        echo "# Regenerate after changing that file, and commit both together."
        "$workdir/venv/bin/pip" freeze --exclude-editable \
            | grep -viE '^(pip|setuptools|wheel|pkg[-_]resources)==' \
            | sort -f
    } > "$API_DIR/$lock_file"

    echo "  wrote apps/api/$lock_file"
}

lock requirements.txt requirements.lock.txt
lock requirements-dev.txt requirements-dev.lock.txt
